### ISSUE TITLE
icons don't work in miranda?

### ISSUE THREAD

**Issue by sagargp** [sagargp/trollicons#28]
on miranda 0.9.28 with SmileyAdd plugin (http://addons.miranda-im.org/details.php?action=viewfile&id=2455). images and .msl file placed in C:\Program Files\Miranda IM\Smileys\Trollicons\, miranda setup with these options: http://i.imgur.com/cs10S.png

**Comment by bijzz** [comment]
Dont know any ruby but for anyone who does it should be quite easy to fix. There is an error with the rakefile. When you look at the output Trollicons.msl you see that the " is inserted into the beginning of the next line instead of the end of each line (linebreak is somewhat flawed).
When that is fixed it seems to be working fine.

Details:
Furthermore the Header Variables of the msl file should be encapsulated with " " so that Miranda can properly grab the values. Also the Icon is set to a filename that does not exist.

**Comment by sagargp** [comment]
this is awesome, thank you. i'll have the bug reporter test it out.

**Comment by unregistered** [comment]
[suspicious] bug reporter?

[xrage] I've been played.

**Comment by sagargp** [comment]
you. you are the bug reporter. [stare] fix it.

**Comment by kpoxo6op** [comment]
I'm the bug reporter.
It works now!
This is great!

**Comment by sagargp** [comment]
[win]

**Comment by kpoxo6op** [comment]
bad link in the bug description:
http://addons.miranda-im.org/details.php?action=viewfile&amp;id=2455

it seems to be GitHub adds "amp;"  after the "&" symbol
