### ISSUE TITLE
There is no size consistency among the rage faces (Adium)

### ISSUE THREAD

**Issue by sagargp** [sagargp/trollicons#8]
The faces don't follow a standard sizing procedure. For example [no] and [okay] should be the same size. The reason for this is because some faces are saved as png's with resolution of around 300dpi and others have around 72dpi. Adium actually renders these differently even if they have the same pixel dimensions. We need to go through and set them all to 72dpi, then ensure that they are properly sized.

**Comment by paradox460** [comment]
This is actually tremendously easy to do, and can be done using [ImageMagick](http://www.imagemagick.org/script/command-line-options.php#density). Use `convert -density 72` to make everything 72 dpi, and presto.

The reason some are 300 is probably because they were a vector i made ages ago, and i had them high-quality, for printing

**Comment by paradox460** [comment]
I said use convert in my last message, i meant to say, use mogrify.

The string I used was `mogrify -units PixelsPerInch -density 72 *.png`. This could probably be worked into the rakefile, and automate the process, so DPI remains the same

**Comment by unregistered** [comment]
Thanks to Paradox for correcting this.
